
---
title: "train-test-split-variation-v.2"
output:
  html_document:
    toc: true
---


```{r}
%md
Define data
```


```{r}
library(SparkR)
sparkR.session()

# Define the file path
training_file_path <- "dbfs:/FileStore/tables/ecom_user_data/customer_propensity_training_sample.csv"
testing_file_path <- "dbfs:/FileStore/tables/ecom_user_data/customer_propensity_testing_sample.csv"

# Read the CSV file into a Spark DataFrame
kaggle_training_data_df <- read.df(training_file_path, source = "csv", header = "true", inferSchema = "true")
kaggle_testing_data_df <- read.df(testing_file_path, source = "csv", header = "true", inferSchema = "true")

# Combine datasets
kaggle_total_data <- rbind(kaggle_training_data_df, kaggle_testing_data_df)

# Bring the data from Spark into R memory - only required for SparkR
kaggle_total_data <- collect(kaggle_total_data)


# Refactor device type variable to be categorical
kaggle_total_data$device_type <- ifelse(
  kaggle_total_data$device_mobile == 1, "mobile",
  ifelse(
    kaggle_total_data$device_computer == 1, "computer",
    "tablet"
  )
)

# Then make sure it's a factor - factor() is similar to as.factor()
kaggle_total_data$device_type <- factor(
  kaggle_total_data$device_type,
  levels = c("mobile", "computer", "tablet")
)

# exlucde UserID
new_kaggle_total_data <- kaggle_total_data[,-1]
str(new_kaggle_total_data)

# set.seed(123)
# ind <- base::sample(1:2, nrow(kaggle_total_data), replace = TRUE, prob = c(0.5, 0.5))
# train_df <- kaggle_total_data[ind == 1, ]
# test_df  <- kaggle_total_data[ind == 2, ]

# Check the structure
# str(train_df) 

# class(kaggle_total_data)
```


```{r}
%md
50-50 split
```


```{r}
%md
Define model
```


```{r}
# Split data
set.seed(1234)
ind <- base::sample(1:2, nrow(new_kaggle_total_data), replace = TRUE, prob = c(0.5, 0.5))
new_train_df_5050 <- new_kaggle_total_data[ind == 1, ]
new_test_df_5050  <- new_kaggle_total_data[ind == 2, ]
```


```{r}
final_model <- glm(ordered ~ basket_icon_click + basket_add_list + basket_add_detail + sort_by + image_picker + account_page_click + detail_wishlist_add + checked_delivery_detail + checked_returns_detail + sign_in + saw_checkout + saw_delivery + saw_account_upgrade + saw_homepage + returning_user + loc_uk + device_type, data = new_train_df_5050, family = "binomial"
)

summary(final_model)
```


```{r}
# test prediction
test_prediction_probs_5050 <- predict(final_model, new_test_df_5050, type = "response")

# Step 1: Create binary prediction from logistic probabilities
test_prediction_results_5050 <- ifelse(test_prediction_probs_5050 > 0.5, 1, 0)

```


```{r}
# Load caret if needed
library(caret)

# Step 4: Prepare data for confusion matrix
test_prediction_results_5050 <- as.factor(test_prediction_results_5050)
new_test_df_actual_5050 <- as.factor(new_test_df_5050$ordered)

# Step 5: Evaluate with confusion matrix
cm <- confusionMatrix(data = test_prediction_results_5050,
                      reference = new_test_df_actual_5050,
                      positive = "1")

# Step 6: Output results
print(cm)

```


```{r}
# Predict probabilities (type = "response" is critical)
test_prediction_probs_5050 <- predict(final_model, new_test_df_5050, type = "response")

```


```{r}
library(pROC)

# Generate ROC curve
roc_test_5050 <- roc(new_test_df_5050$ordered, test_prediction_probs_5050, percent = TRUE)

# Plot ROC
plot.roc(roc_test_5050, 
         print.auc = TRUE,
         auc.polygon = TRUE,
         max.auc.polygon = TRUE,
         auc.polygon.col = "lightblue",
         print.thres = TRUE,
         main = "Test ROC Curve with AUC")

# Get best threshold
coords(roc_test_5050, "best", ret = "threshold", transpose = FALSE)

```


```{r}
%md
60-40
```


```{r}
# Split data
set.seed(1234)
ind <- base::sample(1:2, nrow(new_kaggle_total_data), replace = TRUE, prob = c(0.6, 0.4))
new_train_df_6040 <- new_kaggle_total_data[ind == 1, ]
new_test_df_6040  <- new_kaggle_total_data[ind == 2, ]
```


```{r}
%md
Define data and model
```


```{r}
final_model_6040 <- glm(ordered ~ basket_icon_click + basket_add_list + basket_add_detail + sort_by + image_picker + account_page_click + detail_wishlist_add + checked_delivery_detail + checked_returns_detail + sign_in + saw_checkout + saw_delivery + saw_account_upgrade + saw_homepage + returning_user + loc_uk + device_type, data = new_train_df_6040, family = "binomial"
)

summary(final_model)
```


```{r}
# test prediction
test_prediction_probs_6040 <- predict(final_model_6040, new_test_df_6040, type = "response")

# Step 1: Create binary prediction from logistic probabilities
test_prediction_results_6040 <- ifelse(test_prediction_probs_6040 > 0.5, 1, 0)
```


```{r}
# Load caret if needed
library(caret)

# Step 4: Prepare data for confusion matrix
test_prediction_results_6040 <- as.factor(test_prediction_results_6040)
new_test_df_actual_6040 <- as.factor(new_test_df_6040$ordered)

# Step 5: Evaluate with confusion matrix
cm <- confusionMatrix(data = test_prediction_results_6040,
                      reference = new_test_df_actual_6040,
                      positive = "1")

# Step 6: Output results
print(cm)

```


```{r}
library(pROC)

# Generate ROC curve
roc_test_6040 <- roc(new_test_df_6040$ordered, test_prediction_probs_6040, percent = TRUE)

# Plot ROC
plot.roc(roc_test_6040, 
         print.auc = TRUE,
         auc.polygon = TRUE,
         max.auc.polygon = TRUE,
         auc.polygon.col = "lightblue",
         print.thres = TRUE,
         main = "Test ROC Curve with AUC")

# Get best threshold
coords(roc_test_6040, "best", ret = "threshold", transpose = FALSE)

```


```{r}
%md
70-30
```


```{r}
# Split data
set.seed(1234)
ind <- base::sample(1:2, nrow(new_kaggle_total_data), replace = TRUE, prob = c(0.7, 0.3))
new_train_df_7030 <- new_kaggle_total_data[ind == 1, ]
new_test_df_7030  <- new_kaggle_total_data[ind == 2, ]
```


```{r}
%md
Define data and model
```


```{r}
final_model_7030 <- glm(ordered ~ basket_icon_click + basket_add_list + basket_add_detail + sort_by + image_picker + account_page_click + detail_wishlist_add + checked_delivery_detail + checked_returns_detail + sign_in + saw_checkout + saw_delivery + saw_account_upgrade + saw_homepage + returning_user + loc_uk + device_type, data = new_train_df_7030, family = "binomial"
)

summary(final_model)
```


```{r}
# test prediction
test_prediction_probs_7030 <- predict(final_model_7030, new_test_df_7030, type = "response")

# Step 1: Create binary prediction from logistic probabilities
test_prediction_results_7030 <- ifelse(test_prediction_probs_7030 > 0.5, 1, 0)
```


```{r}
# Load caret if needed
library(caret)

# Step 4: Prepare data for confusion matrix
test_prediction_results_7030 <- as.factor(test_prediction_results_7030)
new_test_df_actual_7030 <- as.factor(new_test_df_7030$ordered)

# Step 5: Evaluate with confusion matrix
cm <- confusionMatrix(data = test_prediction_results_7030,
                      reference = new_test_df_actual_7030,
                      positive = "1")

# Step 6: Output results
print(cm)

```


```{r}
library(pROC)

# Generate ROC curve
roc_test_7030 <- roc(new_test_df_7030$ordered, test_prediction_probs_7030, percent = TRUE)

# Plot ROC
plot.roc(roc_test_7030, 
         print.auc = TRUE,
         auc.polygon = TRUE,
         max.auc.polygon = TRUE,
         auc.polygon.col = "lightblue",
         print.thres = TRUE,
         main = "Test ROC Curve with AUC")

# Get best threshold
coords(roc_test_7030, "best", ret = "threshold", transpose = FALSE)
```


```{r}
%md
80-20
```


```{r}
# Split data
set.seed(1234)
ind <- base::sample(1:2, nrow(new_kaggle_total_data), replace = TRUE, prob = c(0.8, 0.2))
new_train_df_8020 <- new_kaggle_total_data[ind == 1, ]
new_test_df_8020  <- new_kaggle_total_data[ind == 2, ]
```


```{r}
%md
Define data and model
```


```{r}
final_model_8020 <- glm(ordered ~ basket_icon_click + basket_add_list + basket_add_detail + sort_by + image_picker + account_page_click + detail_wishlist_add + checked_delivery_detail + checked_returns_detail + sign_in + saw_checkout + saw_delivery + saw_account_upgrade + saw_homepage + returning_user + loc_uk + device_type, data = new_train_df_8020, family = "binomial"
)

summary(final_model)
```


```{r}
# test prediction
test_prediction_probs_8020 <- predict(final_model_7030, new_test_df_8020, type = "response")

# Step 1: Create binary prediction from logistic probabilities
test_prediction_results_8020 <- ifelse(test_prediction_probs_8020 > 0.5, 1, 0)
```


```{r}
# Load caret if needed
library(caret)

# Step 4: Prepare data for confusion matrix
test_prediction_results_8020 <- as.factor(test_prediction_results_8020)
new_test_df_actual_8020 <- as.factor(new_test_df_8020$ordered)

# Step 5: Evaluate with confusion matrix
cm <- confusionMatrix(data = test_prediction_results_8020,
                      reference = new_test_df_actual_8020,
                      positive = "1")

# Step 6: Output results
print(cm)

```


```{r}
library(pROC)

# Generate ROC curve
roc_test_8020 <- roc(new_test_df_8020$ordered, test_prediction_probs_8020, percent = TRUE)

# Plot ROC
plot.roc(roc_test_8020, 
         print.auc = TRUE,
         auc.polygon = TRUE,
         max.auc.polygon = TRUE,
         auc.polygon.col = "lightblue",
         print.thres = TRUE,
         main = "Test ROC Curve with AUC")

# Get best threshold
coords(roc_test_8020, "best", ret = "threshold", transpose = FALSE)
```
